# Moharrer Taha Project

ูุดุฑูุน ูุญุฑุฑ ูุตูุต ุจุณูุท ุชู ุฅูุดุงุคู ุจูุงุณุทุฉ TahaSoft1.

## โ๏ธ ููุฑุฉ ุงููุดุฑูุน
ุชุทุจูู ูุญุฑุฑ ูุตูุต (Text Editor) ูุญุชูู ุนูู ูุธุงุฆู ุฃุณุงุณูุฉ ูุซู:
- ูุชุญ ุงููููุงุช ุงููุตูุฉ ูุชุญุฑูุฑูุง
- ุญูุธ ุงูุชุบููุฑุงุช
- ุงูุจุญุซ ุฏุงุฎู ุงููุต
- ูุงุฌูุฉ ุณููุฉ ุงูุงุณุชุฎุฏุงู

## ๐ป ููููุฉ ุงูุงุณุชุฎุฏุงู
1. ูู ุจุชุญููู ุงููุดุฑูุน ูู ุฒุฑ **Code โ Download ZIP** ุฃู ุนู ุทุฑูู ุฃูุฑ `git clone`.
2. ูู ุถุบุท ุงููููุงุช ุนูู ุฌูุงุฒู.
3. ุดุบู ุงูููู ุงูุฑุฆูุณู (ูุซูุงู `main.py` ุฃู `index.html` ุญุณุจ ููุน ุงููุดุฑูุน).

## ๐ฆ ุงููุญุชูู
ูุชุถูู ุงููุดุฑูุน:
- ูููุงุช ุงูููุฏ ุงููุตุฏุฑ
- ุจุนุถ ุงูููุงุฑุฏ (ูุซู ุงูุฃููููุงุช ุฃู ูููุงุช ุงููุณุงุนุฏุฉ)

## ๐ ุงูุชุฑุฎูุต
ูุฐุง ุงููุดุฑูุน ููุชูุญ ุงููุตุฏุฑ ููููู ุงุณุชุฎุฏุงูู ูุชุนุฏููู ุจุญุฑูุฉ ูุฃุบุฑุงุถ ุชุนููููุฉ.
